### ISSUE TITLE
Adding co-op copy to website

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/infactcoop.com#103]
We need to talk about being a co-op - why, what that means etc - so we can become a part of CoTech.

This could be a separate page, or just something in the about section...what do you guys reckon? @ivanmauricio  @nogainbar  @maxgerber

**Comment by maxgerber** [comment]
New page! With original illustrations by @nogainbar!

**Comment by lucymk** [comment]
haha YES ideally. but in the short term?
