### ISSUE TITLE
Design changes

### ISSUE THREAD

**Issue by ivanmauricio** [InFact-coop/infactcoop.com#33]
* What is the `our-work` page going to look like? Is it going to be a set of cards like in the landing?
* What is the structure going to be for the individual `our-work` pages? Maybe this should follow ShiftDesign's model
* Are you going to come up with the images of our work wrapped in laptops and phones?
* In `our-approach` page, do we want the cards at the bottom?

**Comment by lucymk** [comment]
Noga todo - 

- [ ] contact us page 
- [ ] assets for projects (Stimmy things, CAST and Blue Cross)
- [ ] airplane image
- [ ] page about FAC
- [ ] try pictures out for headers & about us
- [ ] look into changing weight of logo
- [ ] look at individual project page layouts
